---
title: "Visualizing Batters' Luck Using MLB Statcast Data"
output: html_document
runtime : shiny
---

<style type="text/css">

h1.title {
  font-size: 30px;
  text-align: center;
}
h4.author {
  text-align: center;
}
h4.date {
  text-align: center;
}
</style>

<br>  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
library(baseballr)
library(janitor)
library(forestmangr)
library(gt)
library(reactable)
library(shiny)

source("data_collection_functions.R")
```

<center>
```{r}

  HTML(
      '<div class="form-group shiny-input-container">
        <label for="text">Select MLB Batter To View:</label>
        <input 
          id="player_name" 
          type="text" 
          style="width: 160px; text-align: center" 
          class="form-control" 
          value="" 
          placeholder="ex: Bryce Harper"/>
        </div>'
    )
  actionButton(inputId = "select_player",
               label = "Select!",
               icon = icon("baseball-ball"))
```
</center>

```{r}
data <- eventReactive(input$select_player, {
  withProgress(
  get_table_data(input$player_name),
  message = "Data Takes 10 Seconds To Load",
  detail = "Patience will be rewarded with beauty",
  value = 0.93)
}) 

player_name <- eventReactive(input$select_player, {
  str_to_title(input$player_name)
}) 
```
<br>

```{r}
render_gt({
  data() %>%
    gt(
      rowname_col = "game_year"
      ) %>%
    tab_header(
      title = md(glue::glue("**{player_name()}'s** ***Batted-Ball Statistics***  **Compared to Expected Values**"))
      ) %>%
    tab_source_note(
      md(" Data Source: [MLB.com](https://baseballsavant.mlb.com/statcast_search)")
      ) %>%
    tab_footnote(
      footnote = "Only includes at-bats where the ball was hit in play, not including sacrifice hits.",
      locations = cells_title()
    ) %>%
    tab_footnote(
      footnote = md("Expected values are calculated using a batted ball's launch speed and launch angle. 
      [Learn more here!](https://baseballsavant.mlb.com/leaderboard/expected_statistics)"),
      locations = cells_column_labels(
        columns = vars("expected_ba", "expected_woba")
      )
    ) %>%
    tab_spanner(
      label = "Batting Average",
      columns = vars("ba", "expected_ba", "ba_above_expected")
      ) %>%
    tab_spanner(
      label = "Weighted On-Base Average",
      columns = vars("woba", "expected_woba", "woba_above_expected")
      ) %>%
    cols_align(
      align = "center"
      ) %>%
    cols_width(
      ends_with("ba") ~ px(100),
      ends_with("ed") ~ px(120)
    ) %>%
    data_color(
      columns = c("ba_above_expected", "woba_above_expected"),
      colors = scales::col_numeric(
        palette = c("blue", "white", "red"),
        domain = c(-0.14, 0.14)
        )        
      ) %>%
    opt_row_striping(
      row_striping  = FALSE
    ) %>%
    tab_stubhead(
      label = md("**Season**")
      ) %>%
    tab_options(
      stub.font.weight = "bold"
    ) %>%
    cols_label(
      ba = "AVG",
      expected_ba = "Expected AVG",
      ba_above_expected = md("**AVG Above Expected**"),
      woba = "wOBA",
      expected_woba = "Expected wOBA",
      woba_above_expected = md("**wOBA Above Expected**")
    ) %>%
    tab_style(
      style = cell_borders(
        sides = c("left"),
        color = "#gray",
        weight = px(2.5),
        style = "solid"
      ),
      locations = list(
        cells_body(
        columns = vars("woba"),
        rows = everything()
        )
      )
    ) %>%
    tab_style(
      style = list(
        cell_fill(
          color = "gray",
          alpha = 0.2
          )
      ),
      locations = cells_column_labels(
        columns = vars("ba_above_expected", "woba_above_expected")
      )
    )
  
    # %>%
    # summary_rows(
    #   columns = vars("ba_above_expected", "woba_above_expected"),
    #   fns = list(
    #     " " = ~mean(.)
    #   ),
    #   missing_text = " "
    # )
})
```


